name: ci

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: |
          set -e
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          docker buildx build --push --tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/kernel:${TIMESTAMP} --file Dockerfile.debug .
          docker run --rm ${{ env.REGISTRY }}/${{ github.repository_owner }}/kernel:${TIMESTAMP}

      # - name: Build and push
      #   run: ./build.sh
      #   env:
      #     GITHUB_USERNAME: ${{ github.repository_owner }}
      #     PUSH: 'true'
